ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "Circuito de nível ULV §a")
    event.add("kubejs:advanced_control_circuit", "Circuito de nível LV §c")
    event.add("kubejs:elite_control_circuit", "Circuito de nível MT §b")
    event.add("kubejs:ultimate_control_circuit", "Circuito de nível HV §5")
    event.add("kubejs:ultima_control_circuit", "Circuito de nível EV §4")
    event.add("kubejs:warped_ender_pearl", "Você pode definir um ponto de teletransporte pessoal clicando com o botão direito furtivamente e teletransportar-se para o ponto de teletransporte clicando com o botão direito.")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7Totalmente ligado seletivamente, eficaz mesmo quando rasgado ou danificado")
    event.add("kubejs:black_body_naquadria_supersolid", "§7flui como um líquido, não reflete nenhuma onda eletromagnética e as absorve e transmite perfeitamente.")
    event.add("kubejs:command_wand", "O bloco de comando precisa ser segurado com a mão esquerda e só pode ser colocado em cima do Núcleo de Estabilidade de Criação")
    event.add("kubejs:uruium_coil_block", ["Pode fornecer temperatura de forno de 32.000K para forja de plasma ultradimensional", "Somente esta bobina pode ser usada no modo Stellar Forge"])
    event.add("kubejs:essence_block", "Obtido colocando o bloco ósseo na sala de conversão")
    event.add("kubejs:draconium_block_charged", "Obtido colocando obsidiana infundida com poder de dragão na sala de conversão")
    event.add("minecraft:crimson_stem", "Obtido colocando toras de carvalho na sala de conversão")
    event.add("minecraft:warped_stem", "Obtido colocando toras de bétula na sala de conversão")
    event.add("minecraft:bone_block", "Coloque o Bloco de Cálcio na sala de conversão para obter")
    event.add("minecraft:moss_block", "Obtido colocando blocos de grama na sala de conversão")
    event.add("minecraft:sculk", "Obtido colocando blocos de musgo na sala de conversão")
    event.add("gtceu:magmatter_block", "Obtido jogando um grupo ou mais de lingotes de substância magnética no Portão da Criação")
    event.add("minecraft:command_block", "Obtido ao lançar um bloco de matéria estelar ligada a um fluido magnético no Portão da Criação")
    event.add("minecraft:chain_command_block", "Obtido pela fusão do núcleo do bloco de comando da cadeia com o bloco de comando que está prestes a ser destruído.")
    event.add("minecraft:repeating_command_block", "Obtido pela fusão do Cycle Command Block Core com o Pulse Command Block que está prestes a ser destruído.")
    event.add("ad_astra:oxygen_loader", "§cé apenas sintetizado e não pode produzir oxigênio.")
})