ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "§aULV level circuit")
    event.add("kubejs:advanced_control_circuit", "§cLV level circuit")
    event.add("kubejs:elite_control_circuit", "§bMV level circuit")
    event.add("kubejs:ultimate_control_circuit", "§5HV level circuit")
    event.add("kubejs:ultima_control_circuit", "§4EV level circuit")
    event.add("kubejs:warped_ender_pearl", "You can set a personal teleport point by right-clicking in stealth, and teleport to the teleport point by right-clicking.")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7 Selectively fully bonded, effective even when torn or damaged")
    event.add("kubejs:black_body_naquadria_supersolid", "§7 flows like a liquid, does not reflect any electromagnetic waves, and perfectly absorbs and transmits them.")
    event.add("kubejs:command_wand", "The command block needs to be held in the left hand and can only be placed on top of the Creation Stability Core")
    event.add("kubejs:uruium_coil_block", ["Can provide 32000K furnace temperature for ultra-dimensional plasma forge", "Only this coil can be used in Stellar Forge mode"])
    event.add("kubejs:essence_block", "Obtained by placing the bone block in the conversion room")
    event.add("kubejs:draconium_block_charged", "Obtained by placing obsidian infused with dragon power in the conversion room")
    event.add("minecraft:crimson_stem", "Obtained by placing oak logs in the conversion room")
    event.add("minecraft:warped_stem", "Obtained by placing birch logs in the conversion room")
    event.add("minecraft:bone_block", "Place the Calcium Block in the conversion room to obtain")
    event.add("minecraft:moss_block", "Obtained by placing grass blocks in the conversion room")
    event.add("minecraft:sculk", "Obtained by placing moss blocks in the conversion room")
    event.add("gtceu:magmatter_block", "Obtained by throwing a group or more of magnetic substance ingots into the Gate of Creation")
    event.add("minecraft:command_block", "Obtained by throwing a block of magnetically fluid-bound star matter into the Gate of Creation")
    event.add("minecraft:chain_command_block", "Obtained by merging the chain command block core with the command block that is about to be destroyed.")
    event.add("minecraft:repeating_command_block", "Obtained by merging the Cycle Command Block Core with the Pulse Command Block that is about to be destroyed.")
    event.add("ad_astra:oxygen_loader", "§c is only synthesized and cannot produce oxygen.")
})