ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "Circuito de nível ULV §a")
    event.add("kubejs:advanced_control_circuit", "Circuito de nível LV §c")
    event.add("kubejs:elite_control_circuit", "Circuito de nível MT §b")
    event.add("kubejs:ultimate_control_circuit", "Circuito de nível HV §5")
    event.add("kubejs:ultima_control_circuit", "Circuito de nível EV §4")
    event.add("kubejs:warped_ender_pearl", "Você pode definir um ponto de teletransporte pessoal clicando com o botão direito furtivamente e teletransportar-se para o ponto de teletransporte clicando com o botão direito.")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7Totalmente ligado seletivamente, eficaz mesmo quando rasgado ou danificado")
    event.add("kubejs:black_body_naquadria_supersolid", "§7flui como um líquido, não reflete nenhuma onda eletromagnética e as absorve e transmite perfeitamente.")
    event.add("kubejs:command_wand", "O bloco de comando precisa ser segurado com a mão inábil e só pode ser colocado acima do Núcleo de Estabilidade.")
    event.add("kubejs:uruium_coil_block", ["Pode fornecer temperatura de forno de 32.000K para forja de plasma ultradimensional", "Somente esta bobina pode ser usada no modo Stellar Forge"])
    event.add("kubejs:essence_block", "Pode ser obtido convertendo blocos ósseos na sala de conversão de blocos.")
    event.add("kubejs:draconium_block_charged", "Pode ser obtido convertendo obsidiana infundida com poder de dragão na sala de conversão de blocos.")
    event.add("minecraft:crimson_stem", "Pode ser obtido convertendo toras de carvalho na sala de conversão de blocos")
    event.add("minecraft:warped_stem", "Pode ser obtido convertendo toras de bétula na sala de conversão de blocos.")
    event.add("minecraft:bone_block", "Pode ser obtido convertendo blocos de cálcio na sala de conversão de blocos.")
    event.add("minecraft:moss_block", "Pode ser obtido convertendo blocos de grama na sala de conversão de blocos.")
    event.add("minecraft:sculk", "Pode ser obtido convertendo blocos de musgo na sala de conversão de blocos.")
    event.add("gtceu:magmatter_block", "Obtido jogando um conjunto de Lingotes de Material Magnético no Portão da Criação")
    event.add("minecraft:command_block", "Obtido ao lançar um bloco de matéria estelar ligada a um fluido magnético no Portão da Criação")
    event.add("minecraft:chain_command_block", "Obtido pela fusão do núcleo do bloco de comando da cadeia com o bloco de comando que está prestes a ser quebrado.")
    event.add("minecraft:repeating_command_block", "Obtido pela fusão do núcleo do bloco de comando do ciclo com o bloco de comando da cadeia que está prestes a ser quebrado.")
    event.add("ad_astra:oxygen_loader", "§cé apenas sintetizado e não pode produzir oxigênio.")
})