ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "§aULV level circuit")
    event.add("kubejs:advanced_control_circuit", "§cLV level circuit")
    event.add("kubejs:elite_control_circuit", "§bMV level circuit")
    event.add("kubejs:ultimate_control_circuit", "§5HV level circuit")
    event.add("kubejs:ultima_control_circuit", "§4EV level circuit")
    event.add("kubejs:warped_ender_pearl", "You can set a personal teleport point by right-clicking in stealth, and teleport to the teleport point by right-clicking.")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7Selectively fully bonded, effective even when torn or damaged")
    event.add("kubejs:black_body_naquadria_supersolid", "§7flows like a liquid, does not reflect any electromagnetic waves, and perfectly absorbs and transmits them.")
    event.add("kubejs:command_wand", "The command block needs to be held in the off-hand and can only be placed above the Stability Core.")
    event.add("kubejs:uruium_coil_block", ["Can provide 32000K furnace temperature for ultra-dimensional plasma forge", "Only this coil can be used in Stellar Forge mode"])
    event.add("kubejs:essence_block", "It can be obtained by converting bone blocks in the block conversion room.")
    event.add("kubejs:draconium_block_charged", "It can be obtained by converting obsidian infused with dragon power in the block conversion room.")
    event.add("minecraft:crimson_stem", "Can be obtained by converting oak logs in the block conversion room")
    event.add("minecraft:warped_stem", "It can be obtained by converting birch logs in the block conversion room.")
    event.add("minecraft:bone_block", "It can be obtained by converting calcium blocks in the block conversion room.")
    event.add("minecraft:moss_block", "It can be obtained by converting grass blocks in the block conversion room.")
    event.add("minecraft:sculk", "It can be obtained by converting moss blocks in the block conversion room.")
    event.add("gtceu:magmatter_block", "Obtained by throwing a set of Magnetic Material Ingots into the Gate of Creation")
    event.add("minecraft:command_block", "Obtained by throwing a block of magnetically fluid-bound star matter into the Gate of Creation")
    event.add("minecraft:chain_command_block", "Obtained by merging the chain command block core with the command block that is about to be broken.")
    event.add("minecraft:repeating_command_block", "Obtained by merging the core of the cycle command block with the chain command block that is about to be broken.")
    event.add("ad_astra:oxygen_loader", "§cis only synthesized and cannot produce oxygen.")
})